"""
Build a distilled supplement file for a persona from URLs and/or PDFs.

Usage:
    python scripts/build_context.py --persona uvm_irb \
        --urls https://www.uvm.edu/rpo/institutional-review-board-human-subjects-research \
               https://www.uvm.edu/rpo/irb-policies-and-procedures \
        --pdfs background_documents/PI-checklist-for-new-studies.pdf \
               background_documents/Criteria_for_Approval.pdf \
        --output persona_context/uvm_irb_supplement.md

The script fetches each URL, extracts each PDF, feeds it all to Claude,
and writes a structured, token-efficient supplement file.

Token budget target: ~2,000 tokens per supplement (keeps cost predictable).
"""

import argparse
import os
import sys

import anthropic
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv

load_dotenv(
    dotenv_path=os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env"),
    override=True,
)

try:
    import pypdf
    HAS_PYPDF = True
except ImportError:
    HAS_PYPDF = False


def fetch_url(url: str, char_limit: int = 12000) -> str:
    try:
        r = requests.get(url, timeout=15, headers={"User-Agent": "Mozilla/5.0"})
        r.raise_for_status()
        soup = BeautifulSoup(r.text, "html.parser")
        for tag in soup(["script", "style", "nav", "footer", "header"]):
            tag.decompose()
        text = soup.get_text(separator="\n", strip=True)
        return text[:char_limit]
    except Exception as e:
        return f"[Could not fetch {url}: {e}]"


def extract_pdf(path: str, char_limit: int = 12000) -> str:
    if not HAS_PYPDF:
        return f"[pypdf not installed — run: pip install pypdf]\nFile: {path}"
    try:
        reader = pypdf.PdfReader(path)
        pages = []
        for page in reader.pages:
            pages.append(page.extract_text() or "")
        text = "\n".join(pages)
        return text[:char_limit]
    except Exception as e:
        return f"[Could not extract {path}: {e}]"


def build_supplement(
    persona: str,
    urls: list[str],
    pdfs: list[str],
    output_path: str,
    model: str = "claude-sonnet-4-6",
    token_target: int = 2000,
) -> None:
    client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

    raw_sections = []

    for url in urls:
        print(f"  Fetching {url} ...")
        content = fetch_url(url)
        raw_sections.append(f"--- SOURCE: {url} ---\n{content}")

    for pdf_path in pdfs:
        abs_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))), pdf_path
        )
        print(f"  Extracting {pdf_path} ...")
        content = extract_pdf(abs_path)
        raw_sections.append(f"--- SOURCE: {pdf_path} ---\n{content}")

    if not raw_sections:
        print("No sources provided. Nothing to build.")
        return

    combined = "\n\n".join(raw_sections)

    system = (
        "You are a research documentation specialist. Your job is to distill "
        "raw source material into a concise, high-signal reference document "
        "that will be used as grounding context for an AI reviewer persona. "
        "The output must be factually accurate to the source — do not invent "
        "details. Format as markdown. Prioritize: specific procedures, "
        "checklists, deadlines, named forms/systems, common errors, and "
        "actionable requirements. Omit: repetition, boilerplate, navigation "
        "text, headers-without-content, and anything obvious from general "
        "knowledge. Target approximately "
        + str(token_target)
        + " tokens of output."
    )

    user = (
        f"Persona: {persona}\n\n"
        "Distill the following raw source material into a structured, "
        "token-efficient supplement document. Use clear markdown headers. "
        "Focus on facts a reviewer needs to give accurate, specific advice — "
        "not general background.\n\n"
        + combined
    )

    print(f"  Calling Claude ({model}) to distill {len(combined):,} chars ...")
    response = client.messages.create(
        model=model,
        max_tokens=3000,
        system=system,
        messages=[{"role": "user", "content": user}],
    )

    distilled = response.content[0].text
    tokens_used = response.usage.input_tokens + response.usage.output_tokens

    abs_output = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), output_path
    )
    os.makedirs(os.path.dirname(abs_output), exist_ok=True)

    header = (
        f"# {persona} — Auto-Generated Supplement\n\n"
        f"*Generated by scripts/build_context.py*  \n"
        f"*Sources: {len(urls)} URL(s), {len(pdfs)} PDF(s)*  \n"
        f"*Tokens used to generate: {tokens_used:,}*\n\n"
        "---\n\n"
    )

    with open(abs_output, "w", encoding="utf-8") as f:
        f.write(header + distilled)

    print(f"  Wrote {abs_output}")
    print(f"  API tokens used: {tokens_used:,}")
    print(
        f"  Estimated supplement size: "
        f"~{len(distilled.split()):,} words / "
        f"~{len(distilled) // 4:,} tokens"
    )


def main():
    parser = argparse.ArgumentParser(description="Build a persona context supplement.")
    parser.add_argument("--persona", required=True, help="Persona name (for labeling)")
    parser.add_argument("--urls", nargs="*", default=[], help="URLs to fetch")
    parser.add_argument("--pdfs", nargs="*", default=[], help="PDF paths (relative to repo root)")
    parser.add_argument("--output", required=True, help="Output path (relative to repo root)")
    parser.add_argument(
        "--model",
        default="claude-sonnet-4-6",
        help="Claude model to use for distillation",
    )
    parser.add_argument(
        "--token-target",
        type=int,
        default=2000,
        help="Target output token count (default: 2000)",
    )
    args = parser.parse_args()

    if not os.getenv("ANTHROPIC_API_KEY"):
        print("Error: ANTHROPIC_API_KEY not set in .env or environment.")
        sys.exit(1)

    print(f"Building supplement for: {args.persona}")
    print(f"  URLs: {len(args.urls)}, PDFs: {len(args.pdfs)}")

    build_supplement(
        persona=args.persona,
        urls=args.urls,
        pdfs=args.pdfs,
        output_path=args.output,
        model=args.model,
        token_target=args.token_target,
    )


if __name__ == "__main__":
    main()
